plugins:
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

exclude:
  - "/vendor/"

# Site settings
title: 으리빠 Blog
subtitle:
email: souk0721@gmail.com
name: souk0721
description: >
  noul father
baseurl: ""
url: "https://souk0721.github.io"
cover: "/assets/header_171028.jpg"
logo: "/assets/logo_top.png"

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
inter_post_navigation: false
highlightjs_theme: "darcula"

# Archive settings (see https://github.com/jekyll/jekyll-archives/)
jekyll-archives:
  enabled:
    - categories
    - tags
  layout: 'archive'
  permalinks:
    category: '/:name/'
    tag: '/tags/:name/'


# Google analytics

google_analytics: "UA-120843504-1"

# Category descriptions (for archive pages)
descriptions:
  - cat: posts
    desc: "끄적임 공간"

  - cat: studynote
    desc: "메모는 기억보다 위대하다.
함께 아는 것을 공유했으면 합니다."

# Social icons and sharing options
#
# Social settings are used in two places:
# * In the footer, as links to your personal profiles
# * After each blog post for sharing widgets
#
# Example:
#
# social:
#   - name: Twitter                         # Name of the service
#     icon: twitter                         # Font Awesome icon to use (minus fa- prefix)
#     username: "@TheBenCentra"             # (User) Name to display in the footer link
#     url: https://twitter.com/TheBenCentra # URL of your profile (leave blank to not display in footer)
#     desc: Follow me on Twitter            # Description to display as link title, etc
#     share: true                           # Include in the "Share" section of posts
social:
  - name: Facebook
    icon: facebook
    username: souk0721
    url:
    desc: Friend me on Facebook
    share: true

  - name: GitHub
    icon: github
    username: souk0721
    url: https://github.com/souk0721
    desc: Fork me on GitHub
    share: true

  - name: LinkedIn
    icon: linkedin
    username:
    url:
    desc: Connect with me on LinkedIn
    share: true

  - name: Google+
    icon: google-plus
    username:
    url:
    desc: Add me to your Circles
    share: true

  - name: YouTube
    icon: youtube
    username:
    url:
    desc: Subscribe on YouTube
    share: false

  - name: Instagram
    icon: instagram
    username:
    url:
    desc: Follow me on Instagram
    share: false

  - name: Pinterest
    icon: pinterest
    username:
    url:
    desc: Follow me on Pinterest
    share: false

  - name: SoundCloud
    icon: soundcloud
    username:
    url:
    desc: Follow me on SoundCloud
    share: false

  - name: Tumblr
    icon: tumblr
    username:
    url:
    desc: Follow me on Tumblr
    share: false

  - name: Steam
    icon: steam
    username:
    url:
    desc: Friend me on Steam
    share: false

  - name: Dribbble
    icon: dribbble
    username:
    url:
    desc: Follow me on Dribble
    share: false

  - name: Vimeo
    icon: vimeo-square
    username:
    url:
    desc: Follow me on Vimeo
    share: false

  - name: Vine
    icon: vine
    username:
    url:
    desc: Follow me on Vine
    share: false

  - name: Reddit
    icon: reddit
    username:
    url:
    desc: Share to Reddit
    share: true

  - name: "Hacker News"
    icon: hacker-news
    username:
    url:
    desc: Share to Hacker News
    share: false

# Social sharing protocols
# These are for automatically generating sharing metadata for FB and Twitter
# OS Protocol is for sharing the source of your site, if you're interested. For more, see osprotocol.com


# protocols:
#     fb_image: "/assets/logo.png"
#     fb_image_width: 612
#     fb_image_height: 605
#     fb_image_type: "image/png"
#
#     twitter_image: "/assets/logo.png"

    # os_repo: "https://github.com/bencentra/centrarium.com"
    # os_rcs_type: "git"
    # os_src: "git@github.com:bencentra/centrarium.com.git"
